[build]
builder = "NIXPACKS"
buildCommand = "cd backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd backend && uvicorn simple_api:app --host 0.0.0.0 --port ${PORT:-8000}"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100

[env]
# Railway will automatically provide DATABASE_URL and REDIS_URL
# Add these manually in Railway dashboard:
# SECRET_KEY = "your-secret-key"
# ENVIRONMENT = "production"
# CORS_ORIGINS = "https://your-frontend.vercel.app"
